# vi: set ft=sh expandtab tabstop=4 shiftwidth=4:
if test -n "${bash_profile_guard-}" ; then return 0 ; fi
bash_profile_guard=1

if test -r "${HOME}/.profile" ; then
    . "${HOME}/.profile"
fi

if ! test -f "/etc/suseRegister.conf" ; then
    if test -r "${HOME}/.bashrc" ; then
        . "${HOME}/.bashrc"
    fi
fi
